INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Joni', 'jone@exam.com', 'Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Claudius', 'clad@test.com', 'Jone' ,'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Rabbi','rabi@re.co','Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Quill','rqwi@qw.co','Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Catharina','cath@au.lu','Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Kare','kare@eew.dle','Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Edgard','ed@com.pt','Jone', 'Initiater');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Paton','attpt@eel.de','Jone', 'Master');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Lanita','laneoita@com.pt','Marsh', 'Rookie');
INSERT INTO nos_schema.TRAINER_DATA (first_name, email, password, rank) values ('Ahatron','rabi@ewwre.co','Jone', 'Challenger');
