spring.application.name=Backend_Folders
spring.datasource.driver-class-name=org.postgresql.Driver
# Above is Universal for both local and remote databases.



spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# Above are for local postgres database connection.
# Below is for remote Azure postgres database connection.




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Above is Universal for both local and remote databases.
