spring.application.name=Backend_Folders
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.hikari.schema=nos_schema

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#spring.liquibase.change-log=classpath:changelog/db.changelog-master.xml
#spring.liquibase.liquibase-schema=nos_schema
#spring.liquibase.test-rollback-on-update=true
#spring.liquibase.rollback-file=classpath:changelog/sql/00-rollback.sql
